/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

/**
 *
 * @author matheus
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiCliente = new javax.swing.JMenuItem();
        jmiSair = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jmiConsultaCliente = new javax.swing.JMenu();
        jmiConsultaProduto = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jmiConsultaDia = new javax.swing.JMenu();
        jmiConsultaMes = new javax.swing.JMenuItem();
        jmiConsultaAno = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiNovaVenda = new javax.swing.JMenuItem();
        jmiEmitirNF = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmiAjuda = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmiSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setResizable(false);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setToolTipText("");
        jPanel1.setAutoscrolls(true);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo.png"))); // NOI18N
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Cadastros");

        jmiCliente.setText("Cliente");
        jMenu1.add(jmiCliente);

        jmiSair.setText("Produtos");
        jMenu1.add(jmiSair);
        jMenu1.add(jSeparator1);

        jMenuItem3.setText("Sair");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jmiConsultaCliente.setText("Consultas");

        jmiConsultaProduto.setText("Clientes");
        jmiConsultaCliente.add(jmiConsultaProduto);

        jMenuItem5.setText("Produtos");
        jmiConsultaCliente.add(jMenuItem5);

        jmiConsultaDia.setText("Compras");

        jmiConsultaMes.setText("Dia");
        jmiConsultaDia.add(jmiConsultaMes);

        jmiConsultaAno.setText("Mês");
        jmiConsultaDia.add(jmiConsultaAno);

        jMenuItem6.setText("Ano");
        jmiConsultaDia.add(jMenuItem6);

        jmiConsultaCliente.add(jmiConsultaDia);

        jMenuBar1.add(jmiConsultaCliente);

        jMenu3.setText("Venda");

        jmiNovaVenda.setText("Nova Venda");
        jMenu3.add(jmiNovaVenda);

        jmiEmitirNF.setText("Emitir NF");
        jMenu3.add(jmiEmitirNF);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Suporte");

        jmiAjuda.setText("Ajuda");
        jMenu4.add(jmiAjuda);
        jMenu4.add(jSeparator2);

        jmiSobre.setText("Sobre");
        jMenu4.add(jmiSobre);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(410, 438));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem jmiAjuda;
    private javax.swing.JMenuItem jmiCliente;
    private javax.swing.JMenuItem jmiConsultaAno;
    private javax.swing.JMenu jmiConsultaCliente;
    private javax.swing.JMenu jmiConsultaDia;
    private javax.swing.JMenuItem jmiConsultaMes;
    private javax.swing.JMenuItem jmiConsultaProduto;
    private javax.swing.JMenuItem jmiEmitirNF;
    private javax.swing.JMenuItem jmiNovaVenda;
    private javax.swing.JMenuItem jmiSair;
    private javax.swing.JMenuItem jmiSobre;
    // End of variables declaration//GEN-END:variables
}
